In [154]:
import numpy as np
import matplotlib.pyplot as plt
import copy
import math
import pandas as pd
%matplotlib inline


In [155]:
df = pd.read_csv('heart.csv')
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [156]:



df['Sex'] = df['Sex'].apply(lambda x: 0 if x == 'M' else 1)

X = df[['Age', 'Sex', 'RestingBP', 'Cholesterol']].values  
y = df['HeartDisease'].values  

print("Features (X):", X)
print("Target (y):", y)


Features (X): [[ 40   0 140 289]
 [ 49   1 160 180]
 [ 37   0 130 283]
 ...
 [ 57   0 130 131]
 [ 57   1 130 236]
 [ 38   0 138 175]]
Target (y): [0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1
 0 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0
 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0
 1 0 0 0 1 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 0 0
 0 1 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0
 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1 1
 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1 1 1 0 0 1 0 0 0 0
 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 1 1 0 

In [157]:
print(np.isnan(X).any())  
print(np.isnan(y).any())  


False
False


In [158]:
w = np.zeros(4) 
b = 1

In [159]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)



In [160]:
def sigmoid(z):
    
    #z = np.clip(z, -500, 500)  
    return 1 / (1 + np.exp(-z))


def hypothesis(X, w, b):
    return sigmoid(np.dot(X, w) + b)

In [161]:
def compute_cost(X, y, w, b):
   
    m = X.shape[0]  
    z = np.dot(X, w) + b  
    predictions = sigmoid(z)  
    
    cost = -(1 / m) * np.sum(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))
    return cost


In [162]:
def compute_gradient(X, y, w, b):
    
    m = X.shape[0]  
    z = np.dot(X, w) + b 
    predictions = sigmoid(z) 
   
    error = predictions - y

   
    dj_dw = (1 / m) * np.dot(X.T, error)  
    dj_db = (1 / m) * np.sum(error)       

    return dj_dw, dj_db


In [163]:
def gradient_descent(X, y, w, b, alpha, num_iterations):
   
    cost_history = []

    for i in range(num_iterations):
        
        dj_dw, dj_db = compute_gradient(X, y, w, b)

        
        w = w - alpha * dj_dw
        b = b - alpha * dj_db

       
        if i % 100 == 0:  
            cost = compute_cost(X, y, w, b)
            cost_history.append(cost)
            print(f"Iteration {i}: Cost {cost}")

           
    print(f'w optima: {w},  b optimal: {b}') 
    return w, b, cost_history


In [164]:
w_optimal, b_optimal, _  = gradient_descent(X_scaled, y, w, b, 0.1, 1000)

Iteration 0: Cost 0.7509356799836391
Iteration 100: Cost 0.5856223071949451
Iteration 200: Cost 0.58418346698146
Iteration 300: Cost 0.5841503314926941
Iteration 400: Cost 0.584148987535392
Iteration 500: Cost 0.5841489093561284
Iteration 600: Cost 0.5841489040312782
Iteration 700: Cost 0.5841489036473717
Iteration 800: Cost 0.5841489036191262
Iteration 900: Cost 0.5841489036170321
w optima: [ 0.56378332 -0.60219619  0.16152735 -0.40868211],  b optimal: 0.24322971777103997


In [165]:
import numpy as np
from sklearn.metrics import accuracy_score

def predict(X, w_optimal, b_optimal):
    
    
    z = np.dot(X, w_optimal) + b_optimal

    
    sigmoid_output = 1 / (1 + np.exp(-z))

    
    predictions = (sigmoid_output >= 0.5).astype(int)

    return predictions



X_scaled = scaler.transform(X)


predictions = predict(X_scaled, w_optimal, b_optimal)


accuracy = accuracy_score(y, predictions)

print("Accuracy of the model on original X values:", accuracy * 100, "%")


Accuracy of the model on original X values: 69.28104575163398 %


In [173]:
import numpy as np


new_input = np.array([[50, 0, 100, 200]])


new_input_scaled = scaler.transform(new_input)


z = np.dot(new_input_scaled, w_optimal) + b_optimal


sigmoid = 1 / (1 + np.exp(-z))


predicted_class = (sigmoid >= 0.5).astype(int)


print("Scaled Input:", new_input_scaled)
print("Sigmoid Output:", sigmoid)
print("Predicted Class:", predicted_class)



Scaled Input: [[-0.37241067 -0.51595242 -1.750778    0.01098048]]
Sigmoid Output: [0.51416854]
Predicted Class: [1]


In [167]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

logistic_model = LogisticRegression()

logistic_model.fit(X_train, y_train)

y_pred = logistic_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Coefficient (w):", logistic_model.coef_)
print("Intercept (b):",logistic_model.intercept_)


Accuracy: 0.6358695652173914
Classification Report:
              precision    recall  f1-score   support

           0       0.57      0.55      0.56        77
           1       0.68      0.70      0.69       107

    accuracy                           0.64       184
   macro avg       0.62      0.62      0.62       184
weighted avg       0.63      0.64      0.63       184

Coefficient (w): [[ 0.57956071 -0.58720731  0.18710431 -0.4480872 ]]
Intercept (b): [0.22639313]


In [168]:
import numpy as np
from sklearn.metrics import accuracy_score

def predict(X, w, b):
    
    
    z = np.dot(X, w) + b

    
    sigmoid_output = 1 / (1 + np.exp(-z))

    
    predictions = (sigmoid_output >= 0.5).astype(int)

    return predictions



X_scaled = scaler.transform(X)


predictions = predict(X_scaled, w_optimal, b_optimal)


accuracy = accuracy_score(y, predictions)

print("Accuracy of the model on original X values:", accuracy * 100, "%")


Accuracy of the model on original X values: 69.28104575163398 %
